### ISSUE TITLE
Error when displaying polynomials in IJulia

### ISSUE THREAD

**Issue by rdeits** [blegat/MultivariatePolynomials.jl#22] opened 2017-02-16 19:05 UTC
IJulia throws an error when attempting to automatically display a Polynomial as the result of a cell. To reproduce, just run the following in an IJulia cell:

```julia
using MultivariatePolynomials
@polyvar t
p = t + 0
```

which gives:

```
MethodError: no method matching zero(::Type{Void})
Closest candidates are:
  zero(::Type{Base.LibGit2.Oid}) at libgit2/oid.jl:88
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuildItem}) at pkg/resolve/versionweight.jl:80
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuild}) at pkg/resolve/versionweight.jl:120
  ...

 in ==(::MultivariatePolynomials.Term{true,Void}, ::MultivariatePolynomials.Polynomial{true,Int64}) at /home/rdeits/.julia/v0.5/MultivariatePolynomials/src/comp.jl:128
 in ==(::MultivariatePolynomials.Polynomial{true,Int64}, ::Void) at /home/rdeits/.julia/v0.5/MultivariatePolynomials/src/comp.jl:31
 in != at ./operators.jl:57 [inlined]
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/rdeits/.julia/v0.5/IJulia/src/execute_request.jl:162
```

This happens because `IJulia/execute_request.jl` does a comparison on the result: https://github.com/JuliaLang/IJulia.jl/blob/1cb16ecdac6124a12952bc8948ccf9438b675f3c/src/execute_request.jl#L161 which eventually fails because it tries to construct a `TermContainer{true}(nothing)`.

**Comment by rdeits** [comment] 2017-02-16 19:13
I think the overload at `comp.jl:121` is overly broad. It currently defines `==(::Any, ::TermType)` which causes two different failures in IJulia (one as above where IJulia does `result != nothing` and one later on where it does `result != Out` where `Out::Dict`

**Comment by blegat** [comment] 2017-02-16 21:43
The think is that I do not assume anything on the type of coefficients so `Any` is potentially a coefficient. If I assume that the coefficient is of type `Number` I loose for example JuMP affine expression.
Would it make sense to suggest IJulia to replace its comparisons with `!==` ? Or do you have an other idea ? I am a bit unsure on how to handle this

**Comment by rdeits** [comment] 2017-02-16 22:14
Hm, that's a good point. What about just defining the method for 

```julia
(==){C, T}(y::T, p::TermType{C, T}) = TermContainer{C}(y) == p
```

That is, do you need equality to work for non-polynomial types y which do not match the element type of p?

**Comment by blegat** [comment] 2017-02-16 22:18
It would be nice that `1 == 1.0x ` works.
Actually, this issue may be fixed on Julia v0.6 since they export Base.iszero. If `Base.iszero` is defined for `nothing` and `Dict` we are good :-)

**Comment by rdeits** [comment] 2017-02-16 22:33
I assume you mean `1x == 1.0x`, not `1 == 1.0x`, right?

**Comment by blegat** [comment] 2017-02-17 07:44
Yes, of course. I should have said `0 == 0.0x`

**Comment by rdeits** [comment] 2017-02-17 18:49
I can confirm that this is fixed in #23 . Thank you!

**Comment by rdeits** [comment] 2017-03-09 04:08
One more edge case: 

```julia
using MultivariatePolynomials
@polyvar x y
differentiate(x + 1, y)
```

gives:

```
MethodError: no method matching zero(::Type{Void})
Closest candidates are:
  zero(::Type{Base.LibGit2.Oid}) at libgit2/oid.jl:88
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuildItem}) at pkg/resolve/versionweight.jl:80
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuild}) at pkg/resolve/versionweight.jl:120
  ...

 in ==(::MultivariatePolynomials.Term{true,Void}, ::MultivariatePolynomials.Polynomial{true,Int64}) at /Users/rdeits/.julia/v0.5/MultivariatePolynomials/src/comp.jl:128
 in ==(::MultivariatePolynomials.Polynomial{true,Int64}, ::Void) at /Users/rdeits/.julia/v0.5/MultivariatePolynomials/src/comp.jl:31
 in != at ./operators.jl:57 [inlined]
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/rdeits/.julia/v0.5/IJulia/src/execute_request.jl:162
 in eventloop(::ZMQ.Socket) at /Users/rdeits/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##13#19)() at ./task.jl:360
```

It looks like the `iszero()` check doesn't work for `Void`. Even on 0.6 it throws a MethodError: 

```julia
julia> iszero(nothing)
ERROR: MethodError: no method matching zero(::Void)
```

Maybe just a special overload for comparison with `Void` is in order?

**Comment by blegat** [comment] 2017-03-09 15:07
I don't know if it would be ok to define a Base function for a Base type. Also whether `Void` is zero is subject to philosophical debate :-P
I think the issue is with `IJulia`, they shouldn't do `result != nothing`, they should do `result !== nothing`.
I could add `==(::Void, ::PolyType) = false` as a temporary fix

**Comment by blegat** [comment] 2017-03-09 15:18
I could also check whether `promote_type(S, T) == Any` in which case I skip iszero and return false. But that seems odd.

**Closed** 2017-03-09 15:36 UTC
